# Site settings
title: Jorge Torres
header-img: "img/walle-observant.jpg"
email: your-email@yourdomain.com
description: "Public thoughts about stuff I am working on!"
baseurl: ""
url: "http://torrmal.github.io"
twitter_username: iamjorgetorres
github_username:  torrmal
facebook_username:  imjorgetorres

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
