# Site settings
title: Torrmal's Blog by Jorge Torres
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "Public thoughts about stuff I am working on!"
baseurl: ""
url: "http://torrmal.github.io"
twitter_username: thejorgetorres
github_username:  torrmal
facebook_username:  imjorgetorres

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
